<?php
/**
 * @version 0.1.0
 *
 * @author https://github.com/mc007
 * @license : GPL v2. http://www.gnu.org/licenses/gpl-2.0.html
 * @package XApp\File
 */
function mime_types() {
    return array(
    'css'=>'text/css',
	'json'=>'text/plain',
    'flac'=>'audio/flac',
    'gif'=>'image/gif',
    'gzip'=>'application/x-gzip',
    'gz'=>'application/x-gzip',
    'html'=>'text/html',
    'htm'=>'text/html',
    'ics'=>'text/calendar',
    'ical'=>'text/calendar',
    'jpeg'=>'image/jpeg',
    'jpg'=>'image/jpeg',
    'js'=>'application/javascript',
    'oga'=>'audio/ogg',
    'ogg'=>'audio/ogg',
    'ogv'=>'video/ogg',
    'pdf'=>'application/pdf',
    'png'=>'image/png',
    'svg'=>'image/svg+xml',
    'tar'=>'application/x-tar',
    'tgz'=>'application/x-compressed',
    'tar.gz'=>'application/x-compressed',
    'tif'=>'image/tiff',
    'tiff'=>'image/tiff',
    'txt'=>'text/plain',
    'zip'=>'application/zip',
    'wav'=>'audio/wav',
    'odt'=>'application/vnd.oasis.opendocument.text',
    'ods'=>'application/vnd.oasis.opendocument.spreadsheet',
    'odg'=>'application/vnd.oasis.opendocument.graphics',
    'odp'=>'application/vnd.oasis.opendocument.presentation',
    'pages'=>'application/x-iwork-pages-sffpages',
    'numbers'=>'application/x-iwork-numbers-sffnumbers',
    'keynote'=>'application/x-iwork-keynote-sffkey',
    'kra'=>'application/x-krita',
    'mp3'=>'audio/mpeg',
    'doc'=>'application/msword',
    'docx'=>'application/msword',
    'xls'=>'application/msexcel',
    'xlsx'=>'application/msexcel',
    'php'=>'application/x-php',
    'exe'=>'application/x-ms-dos-executable',
    'pl'=>'application/x-pearl',
    'py'=>'application/x-python',
    'blend'=>'application/x-blender',
    'xcf'=>'application/x-gimp',
    'psd'=>'application/x-photoshop',
    'xml'=>'application/xml',
    'avi'=>'video/x-msvideo',
    'dv'=>'video/dv',
    'm2t'=>'video/mp2t',
    'mp4'=>'video/mp4',
    'm4v'=>'video/mp4',
    'mpg'=>'video/mpeg',
    'mpeg'=>'video/mpeg',
    'mov'=>'video/quicktime',
    'webm'=>'video/webm',
    'wmv'=>'video/x-ms-asf',
    'py'=>'text/x-script.phyton',
    'vcf' => 'text/vcard',
    'vcard' => 'text/vcard',
    'doc'=>'application/msword',
    'docx'=>'application/msword',
    'xls'=>'application/msexcel',
    'xlsx'=>'application/msexcel',
    'ppt'=>'application/mspowerpoint',
    'pptx'=>'application/mspowerpoint',
    'sgf' => 'application/sgf',
    'cdr' => 'application/coreldraw',
    'impress' => 'text/impress',
    'ai' => 'application/illustrator',
    'epub' => 'application/epub+zip',
    'mobi' => 'application/x-mobipocket-ebook',
    'exe' => 'application',
    'msi' => 'application'
    );
}


?>