define(
    ({


        previous:"Précédent",
        done:"Fait",
        publish:"Publier",
        preview:"Aperçu",
        colors:"Couleurs",
        create_category:"Créer Catégorie",
        create_content:"Créer Contenu",
        create_venue:"Créer Lieu",
        create_new_section_tab:"Créer nouveau sous-onglet",
        create_app:"Créer App",
        delete_application:"Supprimer Application",
        select_source:"Sélectionner une source",
        external_link:"Lien Externe",
        rss:"RSS",
        file:"Fichier",
        radio_stream:"Radio Stream",
        upload:"Télécharger",
        register_joomla:"Enregistrer Joomla",
        register_wordpress:"Enregistrer Wordpress",
        register_google_service:"Enregistrer Google Service",
        events:"Évènements",
        general:"Général",
        music:"Musique",
        blog:"Blog",
        new_application:"Nouvelle Application",
        primary_application_platform:"Plateforme d'Application Primaire",
        application_template:"Modèle d'Application",
        create:"Créer",
        my_uploads:"Mes Téléchargements",
        upload_file:"Télécharger Fichier",
        mono_dark:"Mono Noir",
        mono_white:"Mono Blanc",
        blue_buttons:"Icônes Bleus",
        content:"Contenu",
        articles:"Articles",
        locations:"Emplacements",
        xapp_cms:"xapp cms",
        one_year:"Un An",
        monthly:"mensuellement",
        buy:"Acheter",
        discount:"remise",
        billed_monthly:"facturé mensuellement",
        billed_annually:"facturé annuellement",
        learn_more:"Savoir plus",
        purchased:"Acheté",
        select_an_icon:"Sélectionner un Icône",
        until:"jusqu'à",
        title:"Titre",
        apple_launch_screen:"Écran d´Installation Apple",
        background:'Arrière-Plan',
        disabled: "Désactivé",
        pictures: "Photos",
        news: "Actualité",
        places: "Lieux",
        radio: "Radio",
        web: "Web",
        podcasts: "Podcasts",
        videos: "Vidéos",
        facebook:"Facebook",
        twitter:"Twitter",
        edit:"Editer",
        refresh:"Actualiser",
        remove:"Supprimer",
        update_joomla:"Actualiser Joomla",
        update_wordpress:"Actualiser Wordpress",
        update_google_service:"Actualiser Google Service",
        fonts:"Polices",
        titles:"Titres",
        sub_titles:"Sous-Titres",
        font:"Police",
        style:"Style",
        size:"Taille",
        lines:"Lignes",
        color:"Couleur",
        footer_text:"Texte de Pied de Page",
        list_item_detail:"Détail d'Élément de Liste",
        long_text:"Texte Long",
        page_background:"Arrière-Plan de Page",
        list_item_background:"Arrière-Plan d Élément de Liste",
        picture:"Photo",
        transparent:"Transparent",
        content_background:"Arrière-Plan de Contenu(Long)",
        textures:"Textures",
        icon_labels:"Nom des Icônes",
        my_title:"Mon Titre",
        adjust_template:"Ajuster Modèle",
        adjust_icons:"Ajuster Icônes",
        select_image:"Sélectionner Image",
        select_icon:"Sélectionner Icône",
        sci_fi:"Fantastique",
        mono_colored:"Monochrome",
        platik:"Plastique",
        quick:"Rapide",
        advanced:"Avancé",
        navigation_bar:"Barre de Navigation",
        resolution_must_be:"La Resolution doit être"
    })
);
