define([
    "deliteful/Button",
    "xblox/RunScript",
    "delite/Container",
    "delite/register",
    "dojo/has",
    "xdojo/declare",
    "xdojo/has",
    'dcl/dcl',
    'dcl/advise',
    'dcl/mini',
    'xdojo/declare',
    'xide/types',
    'xide/types/Types',
    'xide/utils',
    'xaction/types',
    'xide/utils/StringUtils',
    'xide/utils/HexUtils',
    'xide/utils/HTMLUtils',
    'xide/utils/StoreUtils',
    'xide/utils/WidgetUtils',
    'xide/utils/CIUtils',
    'xide/utils/ObjectUtils',
    'xide/utils/CSSUtils',
    'xfile/types',

    'xide/manager/ContextBase',
    'xapp/manager/Context',
    'xapp/manager/Application',
    "xblox/CSSState",
    "xblox/StyleState",
    'xblox/model/html/SetState',
    'decor/Evented',
    'decor/Invalidating',
    'decor/ObservableArray',
    'decor/features',
    'decor/schedule',
    'decor/sniff',

    'dpointer/events',
    'dpointer/handlers/features',
    'dpointer/handlers/mouse',
    'dpointer/handlers/touch',
    'dpointer/handlers/touchTracker',
    'dpointer/handlers/utils',

    "delite/Template",
    "delite/Widget",
    "delite/handlebars",
    "delite/theme",

    "deliteful/Slider",
    "deliteful/Combobox",
    "deliteful/Select",
    "deliteful/Checkbox",
    "deliteful/RadioButton",
    "deliteful/ToggleButton",
    "deliteful/Switch",
    "deliteful/features",
    "deliteful/ProgressIndicator",
    "deliteful/ViewStack",
    "deliteful/Panel",
    "deliteful/SidePane",
    "deliteful/LinearLayout",
    "deliteful/Button",
    "xdeliteful/Button",
    "deliteful/StarRating",
    "deliteful/ProgressBar",
    "deliteful/list/List",
    "xdeliteful/TabBar",
    "xdeliteful/MediaPlayer",
    "xdeliteful/Script",
    "deliteful/Accordion"    
], function(){
   
});

