define([
    "deliteful/Button",
    "xblox/RunScript",
    "delite/Container",
    "delite/register",
    "dojo/_base/kernel",
    "dojo/_base/lang",
    "dojo/_base/declare",
    "dojo/Deferred",
    "dojo/has",
    "dojo/noob",
    "dojo/node",
    "xdojo/declare",
    "xdojo/has",
    'dcl/dcl',
    'dcl/advise',
    'dcl/mini',
    'dstore/mainr',
    'xdojo/declare',
    'dstore/Filter',

    'xide/types',
    'xide/types/Types',

    'xide/utils',
    'xaction/types',
    'xide/utils/StringUtils',
    'xide/utils/HexUtils',
    'xide/utils/HTMLUtils',
    'xide/utils/StoreUtils',
    'xide/utils/WidgetUtils',
    'xide/utils/CIUtils',
    'xide/utils/ObjectUtils',
    'xide/utils/CSSUtils',
    'xfile/types',

    'xide/manager/ContextBase',
    'xapp/manager/Context',
    'xapp/manager/Application',


    'xblox/mainr',

    "xblox/CSSState",
    "xblox/StyleState",
    'xblox/model/html/SetState',
    'xide/mainr',

    'xfile/manager/FileManager',
    'xwire/main',
    'xcf/mainr',

    'xnode/manager/NodeServiceManager',


    'decor/Evented',
    'decor/Invalidating',
    'decor/ObservableArray',
    'decor/features',
    'decor/schedule',
    'decor/sniff',

    'dpointer/events',
    'dpointer/handlers/features',
    'dpointer/handlers/mouse',
    'dpointer/handlers/touch',
    'dpointer/handlers/touchTracker',
    'dpointer/handlers/utils',

    "delite/Template",
    "delite/Widget",
    "delite/handlebars",
    "delite/theme",

    "deliteful/Slider",
    "deliteful/Combobox",
    "deliteful/Select",
    "deliteful/Checkbox",
    "deliteful/RadioButton",
    "deliteful/ToggleButton",
    "deliteful/Switch",
    "deliteful/features",
    "deliteful/ProgressIndicator",
    "deliteful/ViewStack",
    "deliteful/Panel",
    "deliteful/SidePane",
    "deliteful/LinearLayout",
    "deliteful/Button",
    "xdeliteful/Button",
    "deliteful/StarRating",
    "deliteful/ProgressBar",
    "deliteful/list/List",
    "dojo/selector/_loader",
    "xdeliteful/TabBar",
    "xdeliteful/MediaPlayer",
    "xdeliteful/Script",
    "deliteful/Accordion",
    "dojo/_base/kernel",
    'dojo/Stateful',
    'dojo/query',
    'dojo/cache',
    'dojo/window',
    'dojo/request',
    'dojo/selector/lite',
    "requirejs-domready/domReady"
], function(Button,RunScript,register){
    
});

/*

    'xblox/mainr',

    "xblox/CSSState",
    "xblox/StyleState",
    'xblox/model/html/SetState',
    'xide/mainr',

    //'xfile/manager/FileManager',
    'xwire/main',
    'xcf/mainr',

    'xnode/manager/NodeServiceManager',


    'decor/Evented',
    'decor/Invalidating',
    'decor/ObservableArray',
    'decor/features',
    'decor/schedule',
    'decor/sniff',

    'dpointer/events',
    'dpointer/handlers/features',
    'dpointer/handlers/mouse',
    'dpointer/handlers/touch',
    'dpointer/handlers/touchTracker',
    'dpointer/handlers/utils',

    "delite/Template",
    "delite/Widget",
    "delite/handlebars",
    "delite/theme",

    "deliteful/Slider",
    "deliteful/Combobox",
    "deliteful/Select",
    "deliteful/Checkbox",
    "deliteful/RadioButton",
    "deliteful/ToggleButton",
    "deliteful/Switch",
    "deliteful/features",
    "deliteful/ProgressIndicator",
    "deliteful/ViewStack",
    "deliteful/Panel",
    "deliteful/SidePane",
    "deliteful/LinearLayout",
    "deliteful/Button",
    "xdeliteful/Button",
    "deliteful/StarRating",
    "deliteful/ProgressBar",
    "deliteful/list/List",
    "dojo/selector/_loader",
    "xdeliteful/TabBar",
    "xdeliteful/MediaPlayer",
    "xdeliteful/Script",
    "deliteful/Accordion",
    "requirejs-domready/domReady"
*/