//>>built
define("Shell/ShellManager","dojo/_base/declare dojo/_base/lang xide/factory xide/types xide/utils xide/manager/ManagerBase ./views/ShellView".split(" "),function(l,m,g,k,n,p,q){return l("Shell.xfile.ShellManager",[p],{mainView:null,ctx:null,config:null,panelManager:null,fileManager:null,currentItem:null,persistent:!0,cookiePrefix:"XShell",serverClass:"XShell",ctorArgs:null,currentShell:null,shellPanelContainer:null,shellView:null,autoOpen:!1,getServer:function(){return this.fileManager||xfile.getContext().getFileManager()},
getFileName:function(){var a=this.config.REPO_URL+"/"+this.currentItem.path;return a=a.replace("./","/")},getMainView:function(){return this.mainView||this.panelManager.rootView},onItemSelected:function(a){a&&a.item&&a.item._S&&(this.currentItem=a.item)},_getUrl:function(a){a=this.config.REPO_URL+"/"+a.path;return a=a.replace("./","/")},_createShellView:function(a){var b={LAYOUT_PRESET:1,PANEL_OPTIONS:{ALLOW_NEW_TABS:!1,ALLOW_MULTI_TAB:!1,ALLOW_INFO_VIEW:!1,ALLOW_LOG_VIEW:!1,ALLOW_BREADCRUMBS:!1,
ALLOW_CONTEXT_MENU:!1,ALLOW_LAYOUT_SELECTOR:!1,ALLOW_SOURCE_SELECTOR:!1},ALLOWED_ACTIONS:[0],FILE_PANEL_OPTIONS_LEFT:{LAYOUT:2,AUTO_OPEN:"true"},FILE_PANEL_OPTIONS_MAIN:{LAYOUT:2,AUTO_OPEN:"true"},FILE_PANEL_OPTIONS_RIGHT:{LAYOUT:2,AUTO_OPEN:"false"}},c={selected:!0,delegate:this,item:this.currentItem,options:{},config:b,cookiePrefix:this.cookiePrefix,parentContainer:a};m.mixin(c,this.ctorArgs);c=new q(c,dojo.doc.createElement("div"));a.containerNode.appendChild(c.domNode);c.startup();c.initWithConfig(b);
return a.shellView=c},_createShellPanel:function(){var a=this.getMainView();if(!a.shellPanel&&a&&a.bottomTabContainer){if(this.autoOpen){var b=a.layoutBottom._splitterWidget;if(b)switch(b.state){case "collapsed":case "closed":b.set("state","full")}}var b=a.bottomTabContainer,c=new dijit.layout.ContentPane({title:"Shell",closable:!1,style:"padding:0px;margin:0px;overflow:hidden;"},dojo.doc.createElement("div"));b.addChild(c);b.selectChild(c);b.resize();a.resize();this.shellPanelContainer=b;this.shellView=
this._createShellView(c);a.shellPanel=this.shellView}},getShellView:function(){return this.shellView||this._createShellPanel()},onMainViewReady:function(){this.getShellView()},_registerListeners:function(){this.inherited(arguments);var a=this;g.subscribe(k.EVENTS.ITEM_SELECTED,this.onItemSelected,this);g.subscribe(k.EVENTS.ON_MAIN_VIEW_READY,function(){a.onMainViewReady()},a)},constructor:function(a){this._registerListeners();this.ctorArgs=a},onServerResponse:function(a,b){if(a&&b&&a.owner&&a.owner.onServerResponse)a.owner.onServerResponse(a,
b)},getCurrentPath:function(){if(this.currentItem&&this.panelManager){var a=this.currentItem;if((a=!0===this.currentItem.directory?this.currentItem:this.currentItem._S.getParent(this.currentItem))&&!0===a.directory)return n.buildPath(a.mount,a.path,!1)}return null},runBash:function(a,b,c){var e=this;b=this.base64_encode(b);this.getServer().callMethodEx(this.serverClass,"run",["sh",b,c],function(b){e.onServerResponse(a,b)})},runJavascript:function(a,b){var c=eval(b);if(c)this.onServerResponse(a,c)},
onConsoleCommand:function(a,b){if("sh"===a.type){b=b.replace(/["'`]/g,"");var c=null;a.isLinked()&&(c=this.getCurrentPath());return this.runBash(a,b,c)}if("js"===a.type)return this.runJavascript(a,b)},base64_encode:function(a){var b,c,e,d,h=0,g=0,f="",f=[];if(!a)return a;do b=a.charCodeAt(h++),c=a.charCodeAt(h++),e=a.charCodeAt(h++),d=b<<16|c<<8|e,b=d>>18&63,c=d>>12&63,e=d>>6&63,d&=63,f[g++]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".charAt(b)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".charAt(c)+
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".charAt(e)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".charAt(d);while(h<a.length);f=f.join("");a=a.length%3;return(a?f.slice(0,a-3):f)+"\x3d\x3d\x3d".slice(a||3)}})});
//# sourceMappingURL=ShellManager.js.map